import { test, expect } from "@playwright/test";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { randomUUID } from "node:crypto";
import { createStarterWeddingData, type InvitationRow } from "../../src/lib/invitations";
import type { WeddingData } from "../../src/types/wedding.types";

// Auth users/profiles must already exist in a dedicated EMPTY disposable project.
// No service-role credential, signup, password changes or migration application here.
test.describe.configure({ mode: "serial" });
let a: SupabaseClient, b: SupabaseClient, anon: SupabaseClient;
let ownerA: string, ownerB: string, primary: InvitationRow;
const created: { client: SupabaseClient; id: string }[] = [];
const prefix = `contract-${randomUUID().slice(0, 8)}`;
function required(name: string) {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`Missing ${name}: identify an authorized disposable target; this is not a passing skip.`);
  return name.endsWith("_PASSWORD") ? process.env[name]! : value;
}
test.beforeAll(async () => {
  const url = required("WED_TEST_SUPABASE_URL");
  if (required("WED_TEST_DISPOSABLE_TARGET") !== url ||
      (new URL(url).hostname === "kbwkvbwdxstwsfgkpwbp.supabase.co" && process.env.WED_TEST_ALLOW_SHARED_TARGET !== url)) {
    throw new Error("Refusing an unconfirmed target. Shared production also requires explicit WED_TEST_ALLOW_SHARED_TARGET matching the URL.");
  }
  const key = required("WED_TEST_SUPABASE_ANON_KEY");
  const options = { auth: { persistSession: false, autoRefreshToken: false } };
  a = createClient(url, key, options); b = createClient(url, key, options); anon = createClient(url, key, options);
  for (const [client, suffix] of [[a, "A"], [b, "B"]] as const) {
    const login = await client.auth.signInWithPassword({ email: required(`WED_TEST_OWNER_${suffix}_EMAIL`), password: required(`WED_TEST_OWNER_${suffix}_PASSWORD`) });
    expect(login.error, `Dedicated owner ${suffix} must sign in`).toBeNull();
    expect(login.data.user).not.toBeNull();
    if (suffix === "A") ownerA = login.data.user!.id; else ownerB = login.data.user!.id;
    const rows = await client.from("invitations").select("id");
    expect(rows.error).toBeNull();
    expect(rows.data, "Refusing accounts with existing invitations; never delete personal data for fixture capacity").toEqual([]);
  }
  expect(ownerA).not.toBe(ownerB);
});
test.afterAll(async () => {
  // Only IDs freshly generated by this suite, through their owning client.
  for (const { client, id } of created) {
    const removed = await client.from("invitations").delete().eq("id", id);
    expect(removed.error, `Disposable fixture cleanup ${id}`).toBeNull();
  }
});
function content(id: string, owner: string, slug: string): WeddingData {
  const data = createStarterWeddingData({ id, userId: owner, slug, templateId: "royal", now: "2030-01-01T12:00:00Z" });
  data.couple.bride.name = "Meera Rao"; data.couple.groom.name = "Arjun Shah";
  data.venue.name = "Lotus Hall"; data.venue.address = "123 Lake Road";
  data.events[0].title = "Wedding ceremony"; data.events[0].venue = "Lotus Hall";
  data.sections.showRSVP = false; data.demoContentAcknowledged = true;
  return data;
}
async function create(client: SupabaseClient, owner: string, slug = `${prefix}-${randomUUID().slice(0, 8)}`) {
  const id = randomUUID(); created.push({ client, id });
  return client.rpc("create_invitation_draft", { p_id: id, p_slug: slug, p_template_id: "royal", p_content: content(id, owner, slug) });
}
async function save(client: SupabaseClient, row: InvitationRow, data: WeddingData) {
  return client.rpc("save_invitation_draft", { p_id: row.id, p_expected_revision: row.draft_revision,
    p_template_id: row.template_id, p_content: data });
}
async function publish(row: InvitationRow, slug: string) {
  return a.rpc("publish_invitation_snapshot", { p_id: row.id, p_expected_revision: row.draft_revision, p_requested_slug: slug });
}

test("private rows are inaccessible to anonymous/other owners and direct writes cannot bypass RPCs", async () => {
  const result = await create(a, ownerA); expect(result.error).toBeNull(); primary = result.data;
  const guest = await anon.from("invitations").select("*").eq("id", primary.id);
  expect(guest.error).not.toBeNull();
  const other = await b.from("invitations").select("*").eq("id", primary.id);
  expect(other.error).toBeNull(); expect(other.data).toEqual([]);
  const direct = await a.from("invitations").insert({ id: randomUUID(), user_id: ownerA, slug: `${prefix}-bypass`, template_id: "royal", status: "draft", content: primary.content });
  expect(direct.error).not.toBeNull();
  const updated = await a.from("invitations").update({ status: "published" }).eq("id", primary.id);
  expect(updated.error).not.toBeNull();
  const unauthorized = await save(b, primary, primary.content as WeddingData);
  expect(unauthorized.error?.code).toBe("42501");
  const deletion = await b.from("invitations").delete().eq("id", primary.id).select("id");
  expect(deletion.data).toEqual([]);
});
test("trusted publish rejects invalid content, while draft save permits incomplete fields", async () => {
  const bad = structuredClone(primary.content) as WeddingData;
  bad.couple.bride.name = "Bride"; bad.rsvp = { type: "link", formUrl: "javascript:alert(1)" }; bad.sections.showRSVP = true;
  const saved = await save(a, primary, bad); expect(saved.error).toBeNull(); primary = saved.data;
  const refused = await publish(primary, `${prefix}-public`);
  expect(refused.error?.code).toBe("22023");
  expect(JSON.parse(refused.error!.details)).toEqual(expect.arrayContaining([expect.objectContaining({ path: "couple.bride.name" })]));
  const publicRows = await anon.from("published_invitations").select("*").eq("id", primary.id);
  expect(publicRows.error).toBeNull(); expect(publicRows.data).toEqual([]);
  const restored = await save(a, primary, content(primary.id, ownerA, primary.slug));
  expect(restored.error).toBeNull(); primary = restored.data;
});
test("guest snapshot stays frozen, revision races reject stale writes, unpublish preserves working edits and link", async () => {
  const published = await publish(primary, `${prefix}-public`); expect(published.error).toBeNull(); primary = published.data;
  const stable = primary.slug;
  const left = structuredClone(primary.content) as WeddingData; left.couple.bride.name = "Meera private one";
  const right = structuredClone(primary.content) as WeddingData; right.couple.bride.name = "Meera private two";
  const race = await Promise.all([save(a, primary, left), save(a, primary, right)]);
  expect(race.filter(r => !r.error)).toHaveLength(1); expect(race.find(r => r.error)?.error?.code).toBe("PT409");
  primary = race.find(r => !r.error)!.data;
  const publicRow = await anon.from("published_invitations").select("*").eq("id", primary.id).single();
  expect(publicRow.error).toBeNull(); expect(publicRow.data.content.couple.bride.name).toBe("Meera Rao");
  const offline = await a.rpc("unpublish_invitation_snapshot", { p_id: primary.id, p_expected_revision: primary.draft_revision });
  expect(offline.error).toBeNull(); primary = offline.data;
  expect((primary.content as WeddingData).couple.bride.name).toMatch(/^Meera private/);
  expect((await anon.from("published_invitations").select("id").eq("id", primary.id)).data).toEqual([]);
  const republished = await publish(primary, "names-must-not-rename-link");
  expect(republished.error).toBeNull(); primary = republished.data; expect(primary.slug).toBe(stable);
});
test("a hidden other-owner draft collision allocates a suffix and never renames it", async () => {
  const base = `${prefix}-hidden-collision`;
  expect((await create(b, ownerB, base)).error).toBeNull();
  const next = await create(a, ownerA); expect(next.error).toBeNull();
  expect((await a.from("invitations").select("id").eq("slug", base)).data).toEqual([]);
  const result = await publish(next.data, base); expect(result.error).toBeNull(); expect(result.data.slug).toBe(`${base}-2`);
  const again = await publish(result.data, "new-couple-names"); expect(again.error).toBeNull(); expect(again.data.slug).toBe(`${base}-2`);
});
test("concurrent creation admits exactly the last slot, counting published invitations", async () => {
  const outcomes = await Promise.all(Array.from({ length: 4 }, () => create(a, ownerA)));
  expect(outcomes.filter(r => !r.error)).toHaveLength(1);
  expect(outcomes.filter(r => r.error).map(r => r.error!.details)).toEqual(Array(3).fill("invitation_limit_reached"));
  const total = await a.from("invitations").select("id", { count: "exact" }); expect(total.count).toBe(3);
  const slot = outcomes.find(r => !r.error)!.data as InvitationRow;
  const retry = await a.rpc("create_invitation_draft", { p_id: slot.id, p_slug: slot.slug, p_template_id: slot.template_id, p_content: slot.content });
  expect(retry.error).toBeNull(); expect(retry.data.id).toBe(slot.id);
});
